# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'szablon.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(925, 810)
        self.label = QtWidgets.QLabel(WizardPage)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        #self.label.setPixmap(QtGui.QPixmap("mapa.png"))
        #set qmovie as label
        self.movie = QMovie("10s.gif")
        self.label.setMovie(self.movie)
        self.movie.start()
        self.label_2 = QtWidgets.QLabel(WizardPage)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 991, 801))
        self.label_2.setText("matko boska")
        self.label_2.setPixmap(QtGui.QPixmap("widget_kolno.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        #self.retranslateUi(WizardPage)
        #QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def changePicture(self,WizardPage):
        self.label_2.setPixmap(QtGui.QPixmap("kolno_map.png"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WizardPage = QtWidgets.QWizardPage()
    ui = Ui_WizardPage()
    ui.setupUi(WizardPage)
    ui.changePicture(WizardPage)
    WizardPage.show()
    sys.exit(app.exec_())
