# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'szablon.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
import time
import sys

class Ui_WizardPage(object):

    def __init__(self):
        self.label = None #label na gifa
        self.label_2 = None #label na widget/mape
        self.movie = None #movie do odpalenia gifa
        self.timer = None #timer do zamiany zdjęć

    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(925, 810)
        self.label = QtWidgets.QLabel(WizardPage)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.movie = QMovie("10s.gif")
        self.label.setMovie(self.movie)
        self.movie.start()
        self.label_2 = QtWidgets.QLabel(WizardPage)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 991, 801))
        self.label_2.setText("matko boska")
        self.label_2.setPixmap(QtGui.QPixmap("widget_kolno.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.changeMapPicture)
        self.timer.setInterval(5000)
        self.timer.start()

    def changeMapPicture(self):
        self.label_2.setPixmap(QtGui.QPixmap("kolno_map.png"))

    def changeWidgetPicture(self):
        self.label_2.setPixmap(QtGui.QPixmap("widget_kolno.png"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    WizardPage = QtWidgets.QWizardPage()
    ui = Ui_WizardPage()

    ui.setupUi(WizardPage)
    start = time.time()
    WizardPage.show()
    sys.exit(app.exec_())
